use_local_features: true
use_global_features: true
model_path: "parameters/r101delg_gld_20200814"
image_scales: 0.25
image_scales: 0.35355338
image_scales: 0.5
image_scales: 0.70710677
image_scales: 1.0
image_scales: 1.4142135
image_scales: 2.0
delf_local_config {
  use_pca: false
  max_feature_num: 1000
  score_threshold: 166.1
}
delf_global_config {
  use_pca: false
  image_scales_ind: 3
  image_scales_ind: 4
  image_scales_ind: 5
}
max_image_size: 1024
