# Protos for Tensorflow Seq2Species API.

package(
    default_visibility = ["//visibility:public"],
)

py_proto_library(
    name = "seq2label_py_pb2",
    api_version = 2,
    deps = [":seq2label_proto"],
)

proto_library(
    name = "seq2label_proto",
    srcs = ["seq2label.proto"],
)
