# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker image for running examples in Tensorflow models.
# base_image depends on whether we are running on GPUs or non-GPUs
FROM tensorflow/tensorflow:nightly-gpu

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git

RUN mkdir -p /opt/tf-models
#TODO(karmel): make the data dir configurable
RUN mkdir -p /opt/tf-test-data

RUN git clone https://github.com/tensorflow/models.git /opt/tf-models

WORKDIR /opt/tf-models
# TODO(karmel): Remove this when testing is not on a branch
RUN git checkout feature/kubeflow-testing

ENV PYTHONPATH $PYTHONPATH:/opt/tf-models/official/resnet
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/lib/nvidia:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
COPY hello_tensorflow.py /opt/hello_tensorflow.py
ENTRYPOINT python /opt/hello_tensorflow.py
#ENTRYPOINT python official/resnet/cifar10_download_and_extract.py --data_dir=/opt/tf-test-data
# TODO(karmel): Non-shell version of entrypoint is preferred.
CMD python official/resnet/cifar10_main.py --data_dir=/opt/tf-test-data

