# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker image for running examples in Tensorflow models.
# base_image depends on whether we are running on GPUs or non-GPUs
FROM tensorflow/tensorflow:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git

RUN mkdir -p /opt/tf-models
RUN mkdir -p /opt/tf-test-data
ARG data_dir=/opt/tf-test-data

RUN git clone https://github.com/tensorflow/models.git /opt/tf-models
ENV PYTHONPATH $PYTHONPATH:/opt/tf-models

WORKDIR /opt/tf-models
# TODO(karmel): Remove this when testing is not on a branch
RUN git checkout feature/kubeflow-testing

# Download data into the ARG data_dir, which can optionally be
# passed to the Dockerfile with --data_dir
RUN python models/official/resnet/cifar10_download_and_extract.py --data_dir=$data_dir
ENTRYPOINT ["python", "models/official/resnet/cifar10_test.py"]
