# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker image for running examples in Tensorflow models.
# base_image depends on whether we are running on GPUs or non-GPUs
ARG base_img=tensorflow/tensorflow:latest-gpu
FROM $base_img

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git

RUN mkdir -p /opt/tf-models

ARG data_dir=/opt/tf-test-data
RUN mkdir -p $data_dir

RUN git clone https://github.com/tensorflow/models.git /opt/tf-models

WORKDIR /opt/tf-models
# TODO(karmel): Remove this when testing is not on a branch
RUN git checkout feature/kubeflow-testing

ENV PYTHONPATH $PYTHONPATH:/opt/tf-models/official/resnet

# TODO(karmel): For some reason, files created in my branch can't be run
# directly from the git pull, or so it seems. Copying directly.
COPY run_resnet_cifar10.py /opt/run_resnet_cifar10.py
# TODO(karmel): Non-shell version of entrypoint is preferred.
#ENTRYPOINT python official/testing/end_to_end/run_scripts/run_resnet_cifar10.py \
ENTRYPOINT python /opt/run_resnet_cifar10.py \
  --repo_loc=. --data_dir=/opt/tf-test-data
