package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "faster_rcnn_resnet50_pets.config",
    "ssd_inception_v2_pets.config",
    "ssd_mobilenet_v1_focal_loss_pets.config",
])
