package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "input_ops",
    srcs = ["input_ops.py"],
    srcs_version = "PY2AND3",
)

py_library(
    name = "gru_cell",
    srcs = ["gru_cell.py"],
    srcs_version = "PY2AND3",
)
