py_strict_library = py_library

licenses(["notice"])

package(
    default_visibility = ["//:friends"],  # sequence projection
)

py_strict_library(
    name = "tflite_utils",
    srcs = ["tflite_utils.py"],
    srcs_version = "PY3",
    deps = [
        # package tensorflow
    ],
)

py_strict_library(
    name = "misc_utils",
    srcs = ["misc_utils.py"],
    srcs_version = "PY3",
    deps = [
        # package tensorflow
    ],
)
