package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bulk_feature_extractor",
    hdrs = ["bulk_feature_extractor.h"],
    deps = [
        "@org_tensorflow//tensorflow/core:lib",
    ],
)
