py_binary(
  name = "train",
  srcs = [
    "train.py",
  ],
  srcs_version = "PY2AND3",
  deps = [
    "@org_tensorflow//tensorflow:tensorflow_py",
  ],
)


py_binary(
  name = "export_inference_graph",
  srcs = [
    "export_inference_graph.py",
  ],
  srcs_version = "PY2AND3",
  deps = [
    "@org_tensorflow//tensorflow:tensorflow_py",
  ],
)

py_binary(
  name = "inference_on_image",
  srcs = [
    "inference_on_image.py",
  ],
  srcs_version = "PY2AND3",
  deps = [
    "@org_tensorflow//tensorflow:tensorflow_py",
  ],
)

'''
py_binary(
  name = "coco_inference_on_image",
  srcs = [
    "coco_inference_on_image.py",
  ],
  srcs_version = "PY2AND3",
  deps = [
    "@org_tensorflow//tensorflow:tensorflow_py",
  ],
)
'''
