package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "estimator_util",
    srcs = ["estimator_util.py"],
    srcs_version = "PY2AND3",
    deps = ["//astronet/ops:training"],
)
