model_path: "parameters/delf_gld_20190411/model"
image_scales: .25
image_scales: .3536
image_scales: .5
image_scales: .7071
image_scales: 1.0
image_scales: 1.4142
image_scales: 2.0
delf_local_config {
  use_pca: true
  # Note that for the exported model provided as an example, layer_name and
  # iou_threshold are hard-coded in the checkpoint. So, the layer_name and
  # iou_threshold variables here have no effect on the provided
  # extract_features.py script.
  layer_name: "resnet_v1_50/block3"
  iou_threshold: 1.0
  max_feature_num: 1000
  score_threshold: 100.0
  pca_parameters {
    mean_path: "parameters/delf_gld_20190411/pca/mean.datum"
    projection_matrix_path: "parameters/delf_gld_20190411/pca/pca_proj_mat.datum"
    pca_dim: 128
    use_whitening: false
  }
}
