sh_binary(
    name = "move_ops",
    srcs = ["move_ops.sh"],
    data = [
        "//tf_ops:sequence_string_projection_op_py",
        "//tf_ops:sequence_string_projection_op_v2_py",
        "//tf_ops:tf_custom_ops_py",
	"//tflite_ops:registerer",
    ],
)
