package(
    default_visibility = ["//visibility:public"],
    features = ["-layering_check"],
)

cc_library(
    name = "bulk_feature_extractor",
    hdrs = ["bulk_feature_extractor.h"],
    deps = [
        "//syntaxnet:base",
    ],
)
