py_binary(
    name = "make_parser_spec",
    srcs = ["make_parser_spec.py"],
    deps = [
        "//dragnn/protos:spec_pb2_py",
        "//dragnn/python:spec_builder",
        "@absl_py//absl/flags",
        "@org_tensorflow//tensorflow:tensorflow_py",
    ],
)
